# Example configuration for Jira Fork Tool
# Copy this file to config.yaml and customize for your environment

# Source Jira instance (read-only access required)
source:
  url: "https://source-company.atlassian.net"
  auth:
    type: "api_token"  # api_token, oauth2, jwt
    email: "${JIRA_SOURCE_EMAIL}"
    token: "${JIRA_SOURCE_TOKEN}"
  project_key: "SOURCE"
  verify_ssl: true
  timeout: 30

# Destination Jira instance (read/write access required)
destination:
  url: "https://destination-company.atlassian.net"
  auth:
    type: "api_token"
    email: "${JIRA_DEST_EMAIL}"
    token: "${JIRA_DEST_TOKEN}"
  project_key: "DEST"
  verify_ssl: true
  timeout: 30

# Synchronization settings
sync:
  # Core synchronization options
  preserve_numbers: true          # Maintain ticket number synchronization
  handle_gaps: true              # Handle missing issue numbers
  include_attachments: true      # Transfer file attachments
  include_comments: true         # Transfer comments
  include_worklogs: true         # Transfer work logs
  include_links: true            # Transfer issue links
  
  # Performance settings
  batch_size: 100               # Issues to process in each batch
  max_retries: 3                # Maximum retry attempts
  retry_delay: 5                # Delay between retries (seconds)
  rate_limit_buffer: 0.8        # Use 80% of API rate limit
  
  # Field and user mapping
  field_mappings:
    # Map custom fields between instances
    # "customfield_10001": "customfield_20001"
  
  user_mappings:
    # Map users between instances
    # "old.user@source.com": "new.user@dest.com"
  
  # Gap handling strategy
  gap_strategy: "placeholder"    # placeholder, skip, error
  placeholder_summary: "[PLACEHOLDER] Gap in issue numbering"
  
  # Incremental synchronization
  incremental_enabled: true
  sync_interval: 3600           # Sync interval in seconds
  change_detection_method: "updated"  # updated, audit_log

# Database configuration
database:
  type: "sqlite"                # sqlite, postgresql
  path: "data/jira_fork_tool.db"
  # For PostgreSQL:
  # host: "localhost"
  # port: 5432
  # database: "jira_fork_tool"
  # username: "${DB_USERNAME}"
  # password: "${DB_PASSWORD}"

# Logging configuration
logging:
  level: "INFO"                 # DEBUG, INFO, WARNING, ERROR
  file: "logs/jira_fork_tool.log"
  max_size: 10485760           # 10MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Security configuration
security:
  encrypt_credentials: true
  credential_store: "file"      # file, keyring, vault
  audit_logging: true
  session_timeout: 3600
  max_login_attempts: 3

